spring.application.name=cloud-api

spring.datasource.url=jdbc:mysql://localhost:3306/cloudapi
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
spring.datasource.hikari.connection-timeout=60000
spring.datasource.hikari.maximum-pool-size=10

jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
